---
- name: Despliegue microservice-app (staging/prod auto)
  hosts: all
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive

  vars:
    deploy_user: "{{ ansible_user | default('ubuntu') }}"
    app_dir: "{{ '/opt/microservice-app-stg' if 'staging' in group_names else '/opt/microservice-app' }}"
    compose_file: "{{ 'docker-compose.staging.yml' if 'staging' in group_names else 'docker-compose.prod.yml' }}"
    compose_src_dir: "{{ playbook_dir }}/../../compose"
    base_url: "{{ 'http://localhost:8080' if 'staging' in group_names else 'http://localhost' }}"

  tasks:
    # ---------- Esperar locks de apt ----------
    - name: Esperar locks de APT/dpkg si est치n en uso
      ansible.builtin.shell: |
        set -e
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 3; done
        while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 3; done
      changed_when: false

    # 游뚿 CORRECCI칍N CR칈TICA: Limpieza forzada de locks antes de instalar
    - name: Forzar limpieza de locks de APT/dpkg**
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
        - /var/lib/apt/lists/lock
        - /var/cache/apt/archives/lock
      ignore_errors: true

    - name: Forzar reconfiguraci칩n dpkg**
      ansible.builtin.command: dpkg --configure -a
      changed_when: false
      ignore_errors: true
    # ------------------------------------------------------------------

    # ---------- Prerrequisitos Docker ----------
    - name: Paquetes base
      ansible.builtin.apt:
        name: ['ca-certificates','curl','gnupg','python3']
        state: present
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes
      # Retries ya incluidos
      register: apt_install_result
      retries: 6
      delay: 5
      until: apt_install_result is succeeded

    - name: Crear carpeta de keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Descargar llave GPG de Docker (ASCII)
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true

    - name: Convertir llave a formato gpg (dearmor)
      ansible.builtin.command: >
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Agregar repo de Docker (deb822)
      ansible.builtin.deb822_repository:
        name: docker
        types: [deb]
        uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
        suites: "{{ ansible_distribution_release }}"
        components: [stable]
        signed_by: /etc/apt/keyrings/docker.gpg
        state: present

    # --------- Evitar cuelgues de APT y saltar update si ya hay Docker ----------
    - name: Configurar timeouts/retries de APT (10s, 3 reintentos)
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/99ansible-timeouts
        mode: '0644'
        content: |
          Acquire::http::Timeout "10";
          Acquire::https::Timeout "10";
          Acquire::ftp::Timeout "10";
          Acquire::Retries "3";
          Acquire::http::Pipeline-Depth "0";

    - name: Obtener lista de paquetes instalados
      ansible.builtin.package_facts:
        manager: auto

    - name: Marcar si Docker ya est치 instalado
      ansible.builtin.set_fact:
        docker_installed: "{{ 'docker-ce' in (ansible_facts.packages | default({})) }}"

    - name: Actualizar cache APT (solo si Docker no est치 instalado)
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
      when: not docker_installed
      register: apt_update_result
      retries: 3
      delay: 5
      until: apt_update_result is succeeded

    - name: Instalar Docker Engine, Buildx y Compose
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        force_apt_get: yes

    - name: Agregar usuario al grupo docker
      ansible.builtin.user:
        name: "{{ deploy_user }}"
        groups: docker
        append: yes

    # ---------- Despliegue ----------
    - name: INFO | Host en grupos / paths seleccionados
      ansible.builtin.debug:
        msg: "group_names={{ group_names }} | app_dir={{ app_dir }} | compose={{ compose_file }}"

    - name: Crear directorio de la app
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    # --- PRECHECK: JWT_SECRET debe existir en el entorno del runner ---
    - name: Capturar JWT_SECRET del entorno del runner
      ansible.builtin.set_fact:
        jwt_secret_from_env: "{{ lookup('env','JWT_SECRET') | default('', true) }}"

    - name: Verificar que JWT_SECRET est칠 definido
      ansible.builtin.assert:
        that:
          - jwt_secret_from_env | length > 0
        fail_msg: "JWT_SECRET no est치 definido en variables de entorno del pipeline. Config칰ralo en los secrets/vars del runner."

    - name: Render .env desde plantilla
      ansible.builtin.template:
        src: "{{ compose_src_dir }}/env.j2"
        dest: "{{ app_dir }}/.env"
        mode: '0640'
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
      vars:
        dockerhub_user: "{{ lookup('env','DOCKERHUB_USER') }}"
        image_tag: "{{ lookup('env','IMAGE_TAG') }}"
        jwt_secret: "{{ jwt_secret_from_env }}"

    - name: Copiar docker-compose seg칰n entorno (stg/prod)
      ansible.builtin.copy:
        src: "{{ compose_src_dir }}/{{ compose_file }}"
        dest: "{{ app_dir }}/{{ compose_file }}"
        mode: '0644'
        owner: root
        group: root

    - name: Copiar nginx.conf
      ansible.builtin.copy:
        src: "{{ compose_src_dir }}/nginx.conf"
        dest: "{{ app_dir }}/nginx.conf"
        mode: '0644'
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    # *******************************************************************
    # ********* CORRECCI칍N DE FLUJO DE DESPLIEGUE ***********************
    # *******************************************************************

    - name: Detener y eliminar stack existente (para liberar im치genes antiguas)
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        files:
          - "{{ compose_file }}"
        state: absent
      ignore_errors: true # Puede que el stack no exista la primera vez

    - name: Eliminar imagen antigua de users-api para forzar el pull
      community.docker.docker_image:
        name: "{{ lookup('env','DOCKERHUB_USER') }}/users-api"
        tag: "{{ lookup('env','IMAGE_TAG') }}"
        state: absent
      ignore_errors: true # Si la imagen ya est치 libre o no existe, ignorar.

    - name: Levantar stack con Docker Compose v2 (pull+up)
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        files:
          - "{{ compose_file }}"
        pull: always
        state: present
        remove_orphans: true
      register: compose_up