---
- hosts: prod
  become: true
  vars:
    compose_dir: /opt/microservice-app

  tasks:
    - name: Paquetes base
      ansible.builtin.apt:
        name: [ 'ca-certificates', 'curl', 'gnupg' ]
        state: present
        update_cache: yes

    - name: Agregar repo oficial de Docker
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
      args: { warn: false }

    - name: Instalar Docker CE + buildx + compose
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes

    - name: Asegurar grupo docker para el usuario ubuntu (opcional)
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Crear carpeta de despliegue
      ansible.builtin.file:
        path: "{{ compose_dir }}"
        state: directory
        mode: '0755'

    - name: Subir .env
      ansible.builtin.copy:
        src: "../../compose/.env"
        dest: "{{ compose_dir }}/.env"
        mode: '0644'

    - name: Subir docker-compose
      ansible.builtin.copy:
        src: "../../compose/docker-compose.prod.yml"
        dest: "{{ compose_dir }}/docker-compose.yml"
        mode: '0644'

    - name: Subir nginx.conf
      ansible.builtin.copy:
        src: "../../compose/nginx.conf"
        dest: "{{ compose_dir }}/nginx.conf"
        mode: '0644'

    - name: Pull de imágenes
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        pull: always
        state: present

    - name: Levantar servicios
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        state: present
