---
- hosts: prod
  become: true
  vars:
    compose_dir: /opt/microservice-app

  tasks:
    - name: Paquetes base
      ansible.builtin.apt:
        name: [ 'ca-certificates', 'curl', 'gnupg' ]
        state: present
        update_cache: yes

    - name: Crear carpeta de keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Descargar llave GPG de Docker (ASCII)
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true

    - name: Convertir llave a formato gpg (dearmor)
      ansible.builtin.command: >
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Agregar repo de Docker (formato deb822)
      ansible.builtin.deb822_repository:
        name: docker
        types: [deb]
        uris: https://download.docker.com/linux/ubuntu
        suites: "{{ ansible_distribution_release }}"   # jammy en 22.04
        components: [stable]
        signed_by: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Actualizar cache APT
      ansible.builtin.apt:
        update_cache: yes

    - name: Instalar Docker Engine, Buildx y Compose
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Agregar usuario ubuntu al grupo docker
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Crear directorio de despliegue
      ansible.builtin.file:
        path: "{{ compose_dir }}"
        state: directory
        mode: '0755'

    - name: Subir .env
      ansible.builtin.copy:
        src: "../../compose/.env"
        dest: "{{ compose_dir }}/.env"
        mode: '0644'

    - name: Subir docker-compose
      ansible.builtin.copy:
        src: "../../compose/docker-compose.prod.yml"
        dest: "{{ compose_dir }}/docker-compose.yml"
        mode: '0644'

    - name: Subir nginx.conf
      ansible.builtin.copy:
        src: "../../compose/nginx.conf"
        dest: "{{ compose_dir }}/nginx.conf"
        mode: '0644'

    - name: Pull de imágenes
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        pull: always
        state: present

    - name: Levantar servicios
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}"
        state: present
