---
- name: Despliegue microservice-app (staging/prod auto)
  hosts: all
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive

  vars:
    deploy_user: "{{ ansible_user | default('ubuntu') }}"
    app_dir: "{{ '/opt/microservice-app-stg' if 'staging' in group_names else '/opt/microservice-app' }}"
    compose_file: "{{ 'docker-compose.staging.yml' if 'staging' in group_names else 'docker-compose.prod.yml' }}"
    compose_src_dir: "{{ playbook_dir }}/../../compose"
    base_url: "{{ 'http://localhost:8080' if 'staging' in group_names else 'http://localhost' }}"

  tasks:
    # ---------- Esperar locks de apt ----------
    - name: Esperar locks de APT/dpkg si están en uso
      ansible.builtin.shell: |
        set -e
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 3; done
        while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 3; done
      changed_when: false

    # ---------- Prerrequisitos Docker ----------
    - name: Paquetes base
      ansible.builtin.apt:
        name: ['ca-certificates','curl','gnupg','python3']
        state: present
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes

    - name: Crear carpeta de keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Descargar llave GPG de Docker (ASCII)
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true

    - name: Convertir llave a formato gpg (dearmor)
      ansible.builtin.command: >
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Agregar repo de Docker (deb822)
      ansible.builtin.deb822_repository:
        name: docker
        types: [deb]
        uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
        suites: "{{ ansible_distribution_release }}"
        components: [stable]
        signed_by: /etc/apt/keyrings/docker.gpg
        state: present

    # --------- Evitar cuelgues de APT y saltar update si ya hay Docker ----------
    - name: Configurar timeouts/retries de APT (10s, 3 reintentos)
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/99ansible-timeouts
        mode: '0644'
        content: |
          Acquire::http::Timeout "10";
          Acquire::https::Timeout "10";
          Acquire::ftp::Timeout "10";
          Acquire::Retries "3";
          Acquire::http::Pipeline-Depth "0";

    - name: Obtener lista de paquetes instalados
      ansible.builtin.package_facts:
        manager: auto

    - name: Marcar si Docker ya está instalado
      ansible.builtin.set_fact:
        docker_installed: "{{ 'docker-ce' in (ansible_facts.packages | default({})) }}"

    - name: Actualizar cache APT (solo si Docker no está instalado)
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
      when: not docker_installed
      register: apt_update_result
      retries: 3
      delay: 5
      until: apt_update_result is succeeded

    - name: Instalar Docker Engine, Buildx y Compose
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        force_apt_get: yes

    - name: Agregar usuario al grupo docker
      ansible.builtin.user:
        name: "{{ deploy_user }}"
        groups: docker
        append: yes

    # ---------- Despliegue ----------
    - name: INFO | Host en grupos / paths seleccionados
      ansible.builtin.debug:
        msg: "group_names={{ group_names }} | app_dir={{ app_dir }} | compose={{ compose_file }}"

    - name: Crear directorio de la app
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    # --- PRECHECK: JWT_SECRET debe existir en el entorno del runner ---
    - name: Capturar JWT_SECRET del entorno del runner
      ansible.builtin.set_fact:
        jwt_secret_from_env: "{{ lookup('env','JWT_SECRET') | default('', true) }}"

    - name: Verificar que JWT_SECRET esté definido
      ansible.builtin.assert:
        that:
          - jwt_secret_from_env | length > 0
        fail_msg: "JWT_SECRET no está definido en variables de entorno del pipeline. Configúralo en los secrets/vars del runner."

    - name: Render .env desde plantilla
      ansible.builtin.template:
        src: "{{ compose_src_dir }}/env.j2"
        dest: "{{ app_dir }}/.env"
        mode: '0640'
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
      vars:
        dockerhub_user: "{{ lookup('env','DOCKERHUB_USER') }}"
        image_tag: "{{ lookup('env','IMAGE_TAG') }}"
        jwt_secret: "{{ jwt_secret_from_env }}"

    - name: Copiar docker-compose según entorno (stg/prod)
      ansible.builtin.copy:
        src: "{{ compose_src_dir }}/{{ compose_file }}"
        dest: "{{ app_dir }}/{{ compose_file }}"
        mode: '0644'
        owner: root
        group: root

    - name: Copiar nginx.conf
      ansible.builtin.copy:
        src: "{{ compose_src_dir }}/nginx.conf"
        dest: "{{ app_dir }}/nginx.conf"
        mode: '0644'
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    - name: Levantar stack con Docker Compose v2 (pull+up)
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        files:
          - "{{ compose_file }}"
        pull: always
        state: present
        remove_orphans: true
      register: compose_up

    # ---------- Smoke básico raíz por Nginx ----------
    - name: Smoke GET /
      ansible.builtin.uri:
        url: "{{ base_url }}/"
        return_content: no
        status_code: 200
      register: smoke_root
      failed_when: smoke_root.status != 200

    # ---------- JWT para llamadas protegidas ----------
    - name: Leer .env para extraer JWT_SECRET
      ansible.builtin.slurp:
        src: "{{ app_dir }}/.env"
      register: env_slurp

    - name: Setear jwt_secret desde .env
      ansible.builtin.set_fact:
        jwt_secret: >-
          {{ (env_slurp.content | b64decode).splitlines()
             | select('match','^JWT_SECRET=')
             | first | regex_replace('^JWT_SECRET=','') }}

    - name: Generar JWT en remoto
      ansible.builtin.command: |
        python3 - <<'PY'
        import os,json,base64,hmac,hashlib,time
        def b64url(x): return base64.urlsafe_b64encode(x).rstrip(b'=')
        now=int(time.time())
        h={"alg":"HS256","typ":"JWT"}
        p={"sub":"demo","name":"Demo User","iat":now,"nbf":now-5,"exp":now+3600,"roles":["USER"]}
        sec=os.environ["SECRET"].encode()
        enc=lambda d: b64url(json.dumps(d,separators=(',',':')).encode())
        hdr=enc(h); pld=enc(p)
        sig=b64url(hmac.new(sec, hdr+b'.'+pld, hashlib.sha256).digest())
        print((hdr+b'.'+pld+b'.'+sig).decode())
        PY
      environment:
        SECRET: "{{ jwt_secret }}"
      register: jwt_token

    - name: Esperar /api/users/ vía Nginx (200 con Bearer)
      ansible.builtin.uri:
        url: "{{ base_url }}/api/users/"
        headers:
          Authorization: "Bearer {{ jwt_token.stdout }}"
        return_content: no
        status_code: 200
      register: wait_users
      retries: 40
      delay: 3
      until: wait_users is succeeded and wait_users.status == 200

    - name: Esperar /api/todos/ vía Nginx (200 con Bearer)
      ansible.builtin.uri:
        url: "{{ base_url }}/api/todos/"
        headers:
          Authorization: "Bearer {{ jwt_token.stdout }}"
        return_content: no
        status_code: 200
      register: wait_todos
      retries: 40
      delay: 3
      until: wait_todos is succeeded and wait_todos.status == 200

    - name: Smoke /api/users/ via Nginx
      ansible.builtin.uri:
        url: "{{ base_url }}/api/users/"
        headers:
          Authorization: "Bearer {{ jwt_token.stdout }}"
        return_content: no
        status_code: 200

    - name: Smoke /api/todos/ via Nginx
      ansible.builtin.uri:
        url: "{{ base_url }}/api/todos/"
        headers:
          Authorization: "Bearer {{ jwt_token.stdout }}"
        return_content: no
        status_code: 200
