name: build-auth-api
on:
  push:
    branches: [ main, develop, 'feature/**', 'release/**' ]
    paths: [ 'auth-api/**', '.github/workflows/build-auth-api.yml' ]
  pull_request:
    branches: [ develop ]
    paths: [ 'auth-api/**' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./auth-api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-api:${{ github.sha }}
