name: build-log-processor
on:
  push:
    branches: [ main, develop ]
    paths: [ 'log-message-processor/**', '.github/workflows/build-log-processor.yml' ]
  pull_request:
    paths: [ 'log-message-processor/**' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./log-message-processor
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/log-message-processor:latest
