name: build-users-api
on:
  push:
    branches: [ main, develop ]
    paths: [ 'users-api/**', '.github/workflows/build-users-api.yml' ]
  pull_request:
    paths: [ 'users-api/**' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./users-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/users-api:latest
