name: deploy-prod
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'ops/**'
      - '.github/workflows/deploy-prod.yml'
      - 'frontend/**'
      - 'users-api/**'
      - 'auth-api/**'
      - 'todos-api/**'
      - 'log-message-processor/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Ansible y colección Docker
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
          ansible-galaxy collection install community.docker
      - name: Agregar clave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}
      - name: Comprobar conectividad
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} 'echo ok'
      - name: Ejecutar playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-inventory -i ops/ansible/inventory/hosts.ini --list
          ansible all -i ops/ansible/inventory/hosts.ini -m ping
          ansible-playbook -i ops/ansible/inventory/hosts.ini ops/ansible/playbooks/deploy.yml
